//create User
http://34.100.159.39:6001/user
body:{
  "firstName": "string",
  "lastName": "string",
  "email": "string3",
  "mobileNumber": "string",
  "gender": "string",
  "role":"string",
  "dateOfBirth": "string",
  "address": "string",
  "medicalHistory": "string",
  "password": "string"
}
update : http://34.100.159.39:6001/user/{user._id}
delete : http://34.100.159.39:6001/user/{user._id}

//create nurse
http://34.100.159.39:6001/nurse
body:{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "mobileNumber": "string",
  "dateOfBirth": "string",
  "address": "string",
  "licenseNumber": "string",
  "specification": "string",
  "availiability": "string",
  "password": "string"
}

//create auth/officials
http://34.100.159.39:6001/authorized
body:{
    "firstName": "string",
    "lastName": "string",
    "email": "string",
    "mobileNumber": "string",
    "dateOfBirth": "string",
    "address": "string",
    "roleTitle": "dev",
    "password": "string"
}

// login 
http://34.100.159.39:6001/login/user
http://34.100.159.39:6001/login/nurse
http://34.100.159.39:6001/login/authorized
body:{
    "email": "string",
    "password": "string"
}

//get All users
http://34.100.159.39:6001/Allusers

//get single user
http://34.100.159.39:6001/user/{user._id}

//get All nurse
http://34.100.159.39:6001/Allnurse

//create appointments
http://34.100.159.39:6001/appointments
body{
  "userId": "test",
  "patientName": "test",
  "address": "test",
  "mobileNumber": "test",
  "symptoms": "test",
  "date": "test",
  "time": "test",
  "nurseId": "test",
  "nurseName": "test",
  "nurseSpecialization": "test",
  "paymentMethod": "test",
  "transactionId": "test",
  "amount": 200,
  "status": "test"
}

//get appointments as per user
http://34.100.159.39:6001/appointments/{user._id}
